quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}

quarkus.flyway.migrate-at-start=true

quarkus.swagger-ui.always-include=true

smallrye.jwt.sign.key.location=jwt/privateKey.pem
mp.jwt.verify.publickey.location=jwt/rsaPublicKey.pem
mp.jwt.verify.issuer=allround-auth
