# Development

%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins[0]=http://localhost:3000
%dev.quarkus.http.cors.exposed-headers=Authorization
%dev.quarkus.http.cors.access-control-allow-credentials=true

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=${POSTGRES_USER}
%dev.quarkus.datasource.password=${POSTGRES_PASSWORD}
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}

%dev.quarkus.flyway.migrate-at-start=true

quarkus.swagger-ui.always-include=true

smallrye.jwt.sign.key.location=jwt/privateKey.pem
mp.jwt.verify.publickey.location=jwt/rsaPublicKey.pem
mp.jwt.verify.issuer=allround-auth

quarkus.smallrye-openapi.enabled=true
quarkus.smallrye-openapi.key.store-schema-file-name=openapi-docs
quarkus.smallrye-openapi.store-schema-directory=openapi

quarkus.hibernate-orm.schema-management.strategy=validate

# might need to add the actual value
firebase.storage.bucket=${FIREBASE_STORAGE_BUCKET} 

# Test

%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.flyway.migrate-at-start=true